// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	openIso: (path: string) => typedError<OpenIsoResponse, string>(__TAURI_INVOKE("open_iso", { path })),
	closeIso: (sessionId: SessionId) => __TAURI_INVOKE<boolean>("close_iso", { sessionId }),
	listDirectory: (sessionId: SessionId, path: string, pageRequest: {
	offset: number,
	limit: number,
} | null) => typedError<Page<IsoEntry>, string>(__TAURI_INVOKE("list_directory", { sessionId, path, pageRequest })),
	listEventArchives: (sessionId: SessionId, pageRequest: {
	offset: number,
	limit: number,
} | null) => typedError<Page<IsoEntry>, string>(__TAURI_INVOKE("list_event_archives", { sessionId, pageRequest })),
	listHgarEntries: (resource: ResourceRef, pageRequest: {
	offset: number,
	limit: number,
} | null) => typedError<HgarListing, string>(__TAURI_INVOKE("list_hgar_entries", { resource, pageRequest })),
	openEvs: (resource: ResourceRef) => typedError<EvsDocument, string>(__TAURI_INVOKE("open_evs", { resource })),
	getEvsCommands: (resource: ResourceRef, pageRequest: {
	offset: number,
	limit: number,
} | null) => typedError<EvsCommandPage, string>(__TAURI_INVOKE("get_evs_commands", { resource, pageRequest })),
	getEvsFrames: (resource: ResourceRef, pageRequest: {
	offset: number,
	limit: number,
} | null) => typedError<EvsFramePage, string>(__TAURI_INVOKE("get_evs_frames", { resource, pageRequest })),
	selectEvsVariant: (document: ResourceRef, commandIndex: number, selected: ResourceRef) => typedError<VisualReference, string>(__TAURI_INVOKE("select_evs_variant", { document, commandIndex, selected })),
	readResourceRange: (resource: ResourceRef, offset: number, length: number) => typedError<BinaryChunk, string>(__TAURI_INVOKE("read_resource_range", { resource, offset, length })),
	getImagePreview: (resource: ResourceRef) => typedError<ImagePreview, string>(__TAURI_INVOKE("get_image_preview", { resource })),
	exportResource: (resource: ResourceRef, destination: string) => typedError<ExportResult, string>(__TAURI_INVOKE("export_resource", { resource, destination })),
	getSessionStatus: (sessionId: SessionId) => typedError<SessionStatus, string>(__TAURI_INVOKE("get_session_status", { sessionId })),
};

/* Types */
export type BinaryChunk = {
	offset: number,
	total: number,
	bytes: number[],
};

export type ContainerMember = {
	index: number,
	name: string,
};

export type DiagnosticSeverity = "info" | "warning" | "error";

export type DialogueFrame = {
	commandIndex: number,
	text: string,
	textBytes: number,
	pages: string[],
	speakerId: number,
	speakerName: string,
	expressionId: number,
	expressionName: string,
	audioId: number | null,
	portrait: PortraitReference | null,
	visuals: VisualReference[],
	diagnostics: FormatDiagnostic[],
};

export type EvsCommand = {
	index: number,
	offset: number,
	opcode: number,
	opcodeHex: string,
	name: string,
	parameters: number[],
	content: string | null,
	contentBytes: number,
	rawPayload: number[],
	supported: boolean,
	diagnostics: FormatDiagnostic[],
};

export type EvsCommandPage = {
	page: Page<EvsCommand>,
};

export type EvsDocument = {
	resource: ResourceRef,
	commandCount: number,
	frameCount: number,
	diagnosticCount: number,
	diagnostics: FormatDiagnostic[],
};

export type EvsFramePage = {
	page: Page<DialogueFrame>,
	visualReferences: VisualReference[],
	diagnostics: FormatDiagnostic[],
};

export type ExportResult = {
	destination: string,
	bytesWritten: number,
};

export type FormatDiagnostic = {
	severity: DiagnosticSeverity,
	message: string,
	offset: number,
};

export type GamePath = string;

export type HgarEntry = {
	index: number,
	identifier: number,
	encodedIdentifier: number,
	shortName: string,
	longName: string | null,
	displayName: string,
	compressed: boolean,
	size: number,
	contentOffset: number,
	unknownFirst: number | null,
	unknownLast: number | null,
};

export type HgarListing = {
	resource: ResourceRef,
	version: number,
	entries: Page<HgarEntry>,
};

export type HgptDivision = {
	x: number,
	y: number,
	width: number,
	height: number,
};

export type HgptPixelFormat = "Indexed4" | "Indexed8" | "Rgba8888";

export type ImagePreview = {
	token: string,
	mime: string,
	width: number,
	height: number,
	pixelFormat: HgptPixelFormat,
	divisions: HgptDivision[],
	approximate: boolean,
};

export type IsoEntry = {
	name: string,
	path: string,
	isDirectory: boolean,
	size: number,
	extent: number,
	modified: string | null,
};

export type IsoMetadata = {
	sourcePath: string,
	volumeId: string,
	logicalBlockSize: number,
	volumeSize: number,
};

export type OpenIsoResponse = {
	sessionId: SessionId,
	metadata: IsoMetadata,
	root: Page<IsoEntry>,
};

export type Page<T> = {
	items: T[],
	offset: number,
	total: number,
	hasMore: boolean,
};

export type PageRequest = {
	offset: number,
	limit: number,
};

export type PortraitReference = {
	archivePath: string,
	staticMember: string,
	atlasMember: string,
	resolution: Resolution,
	runtimeHidden: boolean,
};

export type Resolution = { status: "Exact"; value: ResourceRef } | { status: "Variant"; value: ResourceRef[] } | { status: "Missing" } | { status: "Unsupported" };

export type ResourceRef = {
	sessionId: SessionId,
	isoPath: GamePath,
	members: ContainerMember[],
};

export type SessionId = string;

export type SessionStatus = {
	cacheBytes: number,
};

export type VisualReference = {
	commandIndex: number,
	opcode: number,
	requested: string,
	resolution: Resolution,
	evidence: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

